spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: admin
    password: pwd
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-ms: 86400000